version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (*github.com/fatih/color.Color).Fprintf
        - (*github.com/fatih/color.Color).Fprintln
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
