version: 2

builds:
  - binary: aide
    main: ./cmd/aide
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.CommitDate}}

archives:
  - formats:
      - tar.gz
    name_template: "aide_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "sha256sums.txt"

changelog:
  sort: asc

snapshot:
  version_template: "{{ .Version }}-next"

release:
  github:
    owner: jskswamy
    name: aide
  header: '{{ readFile "RELEASE_NOTES.md" }}'
