// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jskswamy/aide/internal/sandbox (interfaces: Sandbox)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_sandbox.go -package=mocks github.com/jskswamy/aide/internal/sandbox Sandbox
//

// Package mocks is a generated GoMock package.
package mocks

import (
	exec "os/exec"
	reflect "reflect"

	sandbox "github.com/jskswamy/aide/internal/sandbox"
	gomock "go.uber.org/mock/gomock"
)

// MockSandbox is a mock of Sandbox interface.
type MockSandbox struct {
	ctrl     *gomock.Controller
	recorder *MockSandboxMockRecorder
	isgomock struct{}
}

// MockSandboxMockRecorder is the mock recorder for MockSandbox.
type MockSandboxMockRecorder struct {
	mock *MockSandbox
}

// NewMockSandbox creates a new mock instance.
func NewMockSandbox(ctrl *gomock.Controller) *MockSandbox {
	mock := &MockSandbox{ctrl: ctrl}
	mock.recorder = &MockSandboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSandbox) EXPECT() *MockSandboxMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockSandbox) Apply(cmd *exec.Cmd, policy sandbox.Policy, runtimeDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", cmd, policy, runtimeDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockSandboxMockRecorder) Apply(cmd, policy, runtimeDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockSandbox)(nil).Apply), cmd, policy, runtimeDir)
}

// GenerateProfile mocks base method.
func (m *MockSandbox) GenerateProfile(policy sandbox.Policy) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateProfile", policy)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateProfile indicates an expected call of GenerateProfile.
func (mr *MockSandboxMockRecorder) GenerateProfile(policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateProfile", reflect.TypeOf((*MockSandbox)(nil).GenerateProfile), policy)
}
