// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jskswamy/aide/internal/secrets (interfaces: EditorRunner)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_editor.go -package=mocks github.com/jskswamy/aide/internal/secrets EditorRunner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEditorRunner is a mock of EditorRunner interface.
type MockEditorRunner struct {
	ctrl     *gomock.Controller
	recorder *MockEditorRunnerMockRecorder
	isgomock struct{}
}

// MockEditorRunnerMockRecorder is the mock recorder for MockEditorRunner.
type MockEditorRunnerMockRecorder struct {
	mock *MockEditorRunner
}

// NewMockEditorRunner creates a new mock instance.
func NewMockEditorRunner(ctrl *gomock.Controller) *MockEditorRunner {
	mock := &MockEditorRunner{ctrl: ctrl}
	mock.recorder = &MockEditorRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditorRunner) EXPECT() *MockEditorRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockEditorRunner) Run(editor string, args []string, stdin io.Reader, stdout, stderr io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", editor, args, stdin, stdout, stderr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockEditorRunnerMockRecorder) Run(editor, args, stdin, stdout, stderr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockEditorRunner)(nil).Run), editor, args, stdin, stdout, stderr)
}
