// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jskswamy/aide/pkg/seatbelt (interfaces: Module,Guard)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_module.go -package=mocks github.com/jskswamy/aide/pkg/seatbelt Module,Guard
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	seatbelt "github.com/jskswamy/aide/pkg/seatbelt"
	gomock "go.uber.org/mock/gomock"
)

// MockModule is a mock of Module interface.
type MockModule struct {
	ctrl     *gomock.Controller
	recorder *MockModuleMockRecorder
	isgomock struct{}
}

// MockModuleMockRecorder is the mock recorder for MockModule.
type MockModuleMockRecorder struct {
	mock *MockModule
}

// NewMockModule creates a new mock instance.
func NewMockModule(ctrl *gomock.Controller) *MockModule {
	mock := &MockModule{ctrl: ctrl}
	mock.recorder = &MockModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModule) EXPECT() *MockModuleMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockModule) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockModuleMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockModule)(nil).Name))
}

// Rules mocks base method.
func (m *MockModule) Rules(ctx *seatbelt.Context) seatbelt.GuardResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rules", ctx)
	ret0, _ := ret[0].(seatbelt.GuardResult)
	return ret0
}

// Rules indicates an expected call of Rules.
func (mr *MockModuleMockRecorder) Rules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rules", reflect.TypeOf((*MockModule)(nil).Rules), ctx)
}

// MockGuard is a mock of Guard interface.
type MockGuard struct {
	ctrl     *gomock.Controller
	recorder *MockGuardMockRecorder
	isgomock struct{}
}

// MockGuardMockRecorder is the mock recorder for MockGuard.
type MockGuardMockRecorder struct {
	mock *MockGuard
}

// NewMockGuard creates a new mock instance.
func NewMockGuard(ctrl *gomock.Controller) *MockGuard {
	mock := &MockGuard{ctrl: ctrl}
	mock.recorder = &MockGuardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuard) EXPECT() *MockGuardMockRecorder {
	return m.recorder
}

// Description mocks base method.
func (m *MockGuard) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockGuardMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockGuard)(nil).Description))
}

// Name mocks base method.
func (m *MockGuard) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockGuardMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockGuard)(nil).Name))
}

// Rules mocks base method.
func (m *MockGuard) Rules(ctx *seatbelt.Context) seatbelt.GuardResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rules", ctx)
	ret0, _ := ret[0].(seatbelt.GuardResult)
	return ret0
}

// Rules indicates an expected call of Rules.
func (mr *MockGuardMockRecorder) Rules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rules", reflect.TypeOf((*MockGuard)(nil).Rules), ctx)
}

// Type mocks base method.
func (m *MockGuard) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockGuardMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockGuard)(nil).Type))
}
